spring.application.name=QuizApp
spring.datasource.url=jdbc:mysql://localhost:3306/quizdb
spring.datasource.username=root
spring.datasource.password=Suchith#13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true